### ISSUE TITLE
Is there a way to go around this?

### ISSUE THREAD

**Issue by ghost** [YeungKC/NewsApi#2]
Because newsapi >=1.0.8 depends on meta ^1.2.2 and every version of flutter_test from sdk depends on meta 1.1.8, newsapi >=1.0.8 is incompatible with flutter_test from sdk.

Is there a way to go around this?

**Comment by YeungKC** [comment]
Thank you for opening an issue.

I will update my dependencies and release a new version later.

**Comment by ghost** [comment]
Thanks for your fast reply, I will be using version 1.0.7 for the mean time.

**Comment by YeungKC** [comment]
Version 1.0.9 has been released and it has passed the tests, please let me know if there are no problems or just close the issue.
